import Head from 'next/head'
import useSWR from 'swr';
import Link from 'next/link'
import { Key, ReactElement } from 'react'
import { fetcher, Post } from '../context/PostContext';
import Layout from '../components/Layout';
import TemplateIndex from '../templates';

const Home = () => {
  const { data, error, isLoading } = useSWR('post-type/posts?sort_by=id&sort_order=desc', fetcher);

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>
  
  return (
    <>
      <Head>
        <title>Juzaweb App</title>
        <meta name="description" content="Generated by create Juzaweb app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateIndex />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Home;
