import Head from 'next/head'
import useSWR from 'swr';
import Link from 'next/link'

const fetcher = (url) => fetch(url).then(r => r.json());

export default function Home() {
  const { data, error, isLoading } = useSWR('http://cms.local/api/post-type/posts?sort_by=id&sort_order=desc', fetcher);

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>
  
  return (
    <>
      <Head>
        <title>Juzaweb App</title>
        <meta name="description" content="Generated by create Juzaweb app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.data.map((item, index) => (
          <div key={index}>
          <h5><Link href={`post/${item.slug}`}>{item.title}</Link></h5>
        </div>
        ))}
      </main>
    </>
  )
}
